### PR TITLE
Fix null-termination errors in MakeDigest

### LINKED ISSUE #88: proto::MakeDigest has buffer underflow / overflow errors

### PR DESCRIPTION
**Pull request by ZacharyEspiritu**
Resolves #88.

For simplicity, I converted the `string_view` back to a `std::string`—can always add it back if needed.

### CODE REVIEW

File: src/backing/client/grpc_client/proto_util.cc [hunk 1]
```diff
@@ -74,17 +73,17 @@ StatusCode MapStatusCode(grpc::StatusCode const& code) {
 }  // namespace
 
 google::cloud::kms::v1::Digest MakeDigest(DigestCase type,
-                                          absl::string_view digest_bytes) {
+                                          std::string digest_bytes) {
   google::cloud::kms::v1::Digest proto_digest;
   switch (type) {
     case DigestCase::kSha256:
-      proto_digest.set_sha256(digest_bytes.data());
+      proto_digest.set_sha256(digest_bytes.data(), digest_bytes.length());
```
Comment (ajfeldma-google) [inline src/backing/client/grpc_client/proto_util.cc]: You should just be able to write: `proto_digest.set_sha256(digest_bytes)` as long as `digest_bytes` is a `std::string` rather than an `absl::string_view`.

https://developers.google.com/protocol-buffers/docs/reference/cpp-generated#proto3_string

**Review by ajfeldma-google — CHANGES_REQUESTED** [review]

**Review by ajfeldma-google — APPROVED** [review]

File: src/backing/client/grpc_client/proto_util.cc [hunk 2]
```diff
@@ -74,17 +73,17 @@ StatusCode MapStatusCode(grpc::StatusCode const& code) {
 }  // namespace
 
 google::cloud::kms::v1::Digest MakeDigest(DigestCase type,
-                                          absl::string_view digest_bytes) {
+                                          std::string digest_bytes) {
```
Comment (tonyliaoss) [inline src/backing/client/grpc_client/proto_util.cc:76]: Leave a comment here to note why you shouldn't use `absl::string_view`?

File: src/backing/client/grpc_client/proto_util.h [hunk 3]
```diff
@@ -32,7 +31,7 @@ namespace backing {
 
 // Factory function which creates an protobuf `Digest`.
 google::cloud::kms::v1::Digest MakeDigest(DigestCase type,
-                                          absl::string_view digest_bytes);
+                                          std::string digest_bytes);
```
Comment (tonyliaoss) [inline src/backing/client/grpc_client/proto_util.h:34]: Leave a comment here too.

**Review by tonyliaoss — APPROVED** [review]
